### ISSUE TITLE
Create Routes Module - Google Maps API (Backend)

### ISSUE THREAD

**Issue by MasWill** [hungrr/hungrr-app#5]
Create the routes module that handles the requests to the Google Maps API with given location data. I anticipate that it would be one function that takes location data, a range, and restaurant IDs as input and sends a request to the maps api to get every restaurant in a given range. This may require a loop. After that, find out the format of what google sends in the response, and format that to the restaurant model. Then return a list of these models which will end up being our stack.

**Comment by zeyf** [comment]
In progress
